# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    serializer:
        # @see https://api-platform.com/docs/core/serialization/#configuration
        mapping:
            paths: ['%kernel.project_dir%/config/packages/serializer']
        # @see https://symfony.com/doc/current/serializer.html#serializer-context
        default_context:
            enable_max_depthe: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
