App\Entity\Comment:
  attributes:
    route_prefix: /v1

  properties:
    post:
      attributes:
        openapi_context:
          description: コメント先の投稿
    body:
      attributes:
        openapi_context:
          description: コメントの本文
    isBanned:
      attributes:
        openapi_context:
          description: BANされているかどうか

  collectionOperations:
    get:
      path: /posts/{id}/comments
      openapi_context:
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
            description: 投稿ID
    post:
      path: /posts/{id}/comments
      controller: App\Controller\Comment\CollectionPostController

  itemOperations:
    get:
      controller: ApiPlatform\Core\Action\NotFoundAction
      read: false
      output: false
      openapi_context:
        description: '#hidden'
    ban:
      method: put
      path: /comments/{id}/ban
      controller: App\Controller\Comment\ItemBanController
      input: false
      openapi_context:
        description: 'Creates a Comment resource. #withoutRequestBody #withoutLinks'
