App\Entity\Comment:
  attributes:
    route_prefix: /v1
    normalization_context:
      groups: [comment:read]
    denormalization_context:
      groups: [comment:write]

  collectionOperations:
    get:
      path: /posts/{id}/comments
      openapi_context:
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
            description: 投稿ID
    post:
      path: /posts/{id}/comments
      controller: App\Controller\Comment\CollectionPostController

  itemOperations:
    get:
      controller: ApiPlatform\Core\Action\NotFoundAction
      read: false
      output: false
      openapi_context:
        description: '#hidden'
    ban:
      method: put
      path: /comments/{id}/ban
      controller: App\Controller\Comment\ItemBanController
      input: false
      openapi_context:
        description: 'Creates a Comment resource. #withoutRequestBody #withoutLinks'
