resources:
  App\Entity\Comment:
    routePrefix: /v1
    normalizationContext:
      groups: [comment:read]
    denormalizationContext:
      groups: [comment:write]

    operations:

      comments_getCollection:
        class: ApiPlatform\Metadata\GetCollection
        uriTemplate: /posts/{postId}/comments
        uriVariables:
          postId:
            fromClass: App\Entity\Post
            toProperty: post
        provider: App\State\Provider\Comment\GetCollectionProvider

      comments_post:
        class: ApiPlatform\Metadata\Post
        uriTemplate: /posts/{postId}/comments
        uriVariables:
          postId:
            fromClass: App\Entity\Post
            toProperty: post
        provider: App\State\Provider\Comment\PostProvider

      comments_get:
        class: ApiPlatform\Metadata\Get
        controller: ApiPlatform\Action\NotFoundAction
        read: false
        output: false
        openapi:
          description: '#hidden'

      comments_ban:
        class: ApiPlatform\Metadata\Put
        uriTemplate: /comments/{id}/ban
        controller: App\Controller\Comment\BanController
        input: false
        openapi:
          description: 'Creates a Comment resource. #noRequestBody'
