App\Entity\Post:
  attributes:
    route_prefix: /v1

  itemOperations:
    latest:
      method: get
      path: /posts/latest
    putLatest:
      method: put
      path: /posts/latest
    patch: ~
    delete: ~
