App\Entity\Post:
  attributes:
    route_prefix: /v1

  itemOperations:
    latest:
      method: get
      path: /posts/latest
      controller: App\Controller\Post\ItemLatestController
      read: false
    putLatest:
      method: put
      path: /posts/latest
      controller: App\Controller\Post\ItemPutLatestController
      read: false
    patch: ~
    delete: ~
