properties:
  App\Entity\Post\Author:
    birthDate:
      openapiContext:
        format: date

resources:
  App\Entity\Post:
    routePrefix: /v1
    normalizationContext:
      groups: [post:read]
    denormalizationContext:
      groups: [post:write]

    operations:

      posts_getCollection:
        class: ApiPlatform\Metadata\GetCollection
        filters:
          - post.search_filter

      posts_post:
        class: ApiPlatform\Metadata\Post

      posts_getLatest:
        class: ApiPlatform\Metadata\Get
        uriTemplate: /posts/latest
        provider: App\State\Provider\Post\GetLatestProvider

      posts_putLatest:
        class: ApiPlatform\Metadata\Put
        uriTemplate: /posts/latest
        provider: App\State\Provider\Post\GetLatestProvider

      posts_patch:
        class: ApiPlatform\Metadata\Patch

      posts_delete:
        class: ApiPlatform\Metadata\Delete
