# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #
    # API Platform
    #

    # @see https://api-platform.com/docs/core/operation-path-naming/
    App\ApiPlatform\LowerCamelCasePathSegmentNameGenerator: ~

    # @see https://api-platform.com/docs/core/openapi/#overriding-the-openapi-specification
    App\ApiPlatform\OpenApiFactory:
        decorates: api_platform.openapi.factory
        autoconfigure: false

    App\ApiPlatform\IriConverter:
        decorates: api_platform.iri_converter
        arguments:
            $routeNameResolver: '@api_platform.route_name_resolver'

    #
    # API Platform - Filters
    # @see https://api-platform.com/docs/core/filters/
    #

    # Post

    post.search_filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - title: partial
              body: partial
        tags: [api_platform.filter]
        autowire: false
        autoconfigure: false
