App\Entity\Comment:
  attributes:
    id:
      groups:
        - comment:read
        - post:read
    post:
      max_depth: 1
      groups:
        - comment:read
        - comment:write
        - post:read
    body:
      groups:
        - comment:read
        - comment:write
        - post:read
